 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/solutions", type: :request do
  
  # Solution. As you add validations to Solution, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Solution.create! valid_attributes
      get solutions_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      solution = Solution.create! valid_attributes
      get solution_url(solution)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_solution_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      solution = Solution.create! valid_attributes
      get edit_solution_url(solution)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Solution" do
        expect {
          post solutions_url, params: { solution: valid_attributes }
        }.to change(Solution, :count).by(1)
      end

      it "redirects to the created solution" do
        post solutions_url, params: { solution: valid_attributes }
        expect(response).to redirect_to(solution_url(Solution.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Solution" do
        expect {
          post solutions_url, params: { solution: invalid_attributes }
        }.to change(Solution, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post solutions_url, params: { solution: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested solution" do
        solution = Solution.create! valid_attributes
        patch solution_url(solution), params: { solution: new_attributes }
        solution.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the solution" do
        solution = Solution.create! valid_attributes
        patch solution_url(solution), params: { solution: new_attributes }
        solution.reload
        expect(response).to redirect_to(solution_url(solution))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        solution = Solution.create! valid_attributes
        patch solution_url(solution), params: { solution: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested solution" do
      solution = Solution.create! valid_attributes
      expect {
        delete solution_url(solution)
      }.to change(Solution, :count).by(-1)
    end

    it "redirects to the solutions list" do
      solution = Solution.create! valid_attributes
      delete solution_url(solution)
      expect(response).to redirect_to(solutions_url)
    end
  end
end
